#Code Generated by Sidekick if for learning and experimentation purpose only.
FROM python:3.10.2-slim as base

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

COPY . .

CMD python ./app.py